//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseballEFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appearances
    {
        public int yearID { get; set; }
        public string teamID { get; set; }
        public string lgID { get; set; }
        public string playerID { get; set; }
        public Nullable<int> G_all { get; set; }
        public Nullable<int> GS { get; set; }
        public Nullable<int> G_batting { get; set; }
        public Nullable<int> G_defense { get; set; }
        public Nullable<int> G_p { get; set; }
        public Nullable<int> G_c { get; set; }
        public Nullable<int> G_1b { get; set; }
        public Nullable<int> G_2b { get; set; }
        public Nullable<int> G_3b { get; set; }
        public Nullable<int> G_ss { get; set; }
        public Nullable<int> G_lf { get; set; }
        public Nullable<int> G_cf { get; set; }
        public Nullable<int> G_rf { get; set; }
        public Nullable<int> G_of { get; set; }
        public Nullable<int> G_dh { get; set; }
        public Nullable<int> G_ph { get; set; }
        public Nullable<int> G_pr { get; set; }
    }
}
