//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseballEFW
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseballEntities : DbContext
    {
        public BaseballEntities()
            : base("name=BaseballEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appearances> Appearances { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<Salaries> Salaries { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
    }
}
