//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseballEFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams
    {
        public int yearID { get; set; }
        public string lgID { get; set; }
        public string teamID { get; set; }
        public string franchID { get; set; }
        public string divID { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> G { get; set; }
        public Nullable<int> Ghome { get; set; }
        public Nullable<int> W { get; set; }
        public Nullable<int> L { get; set; }
        public string DivWin { get; set; }
        public string WCWin { get; set; }
        public string LgWin { get; set; }
        public string WSWin { get; set; }
        public Nullable<int> R { get; set; }
        public Nullable<int> AB { get; set; }
        public Nullable<int> H { get; set; }
        public Nullable<int> C2B { get; set; }
        public Nullable<int> C3B { get; set; }
        public Nullable<int> HR { get; set; }
        public Nullable<int> BB { get; set; }
        public Nullable<int> SO { get; set; }
        public Nullable<int> SB { get; set; }
        public Nullable<int> CS { get; set; }
        public Nullable<int> HBP { get; set; }
        public Nullable<int> SF { get; set; }
        public Nullable<int> RA { get; set; }
        public Nullable<int> ER { get; set; }
        public Nullable<double> ERA { get; set; }
        public Nullable<int> CG { get; set; }
        public Nullable<int> SHO { get; set; }
        public Nullable<int> SV { get; set; }
        public Nullable<int> IPouts { get; set; }
        public Nullable<int> HA { get; set; }
        public Nullable<int> HRA { get; set; }
        public Nullable<int> BBA { get; set; }
        public Nullable<int> SOA { get; set; }
        public Nullable<int> E { get; set; }
        public Nullable<int> DP { get; set; }
        public Nullable<double> FP { get; set; }
        public string name { get; set; }
        public string park { get; set; }
        public Nullable<int> attendance { get; set; }
        public Nullable<int> BPF { get; set; }
        public Nullable<int> PPF { get; set; }
        public string teamIDBR { get; set; }
        public string teamIDlahman45 { get; set; }
        public string teamIDretro { get; set; }
    }
}
