//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventanas.SrvEquipos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvEquipos.ISrvEquipos")]
    public interface ISrvEquipos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvEquipos/GetAñoInicial", ReplyAction="http://tempuri.org/ISrvEquipos/GetAñoInicialResponse")]
        int GetAñoInicial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvEquipos/GetAñoInicial", ReplyAction="http://tempuri.org/ISrvEquipos/GetAñoInicialResponse")]
        System.Threading.Tasks.Task<int> GetAñoInicialAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvEquipos/GetAñoFinal", ReplyAction="http://tempuri.org/ISrvEquipos/GetAñoFinalResponse")]
        int GetAñoFinal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvEquipos/GetAñoFinal", ReplyAction="http://tempuri.org/ISrvEquipos/GetAñoFinalResponse")]
        System.Threading.Tasks.Task<int> GetAñoFinalAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISrvEquiposChannel : Ventanas.SrvEquipos.ISrvEquipos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SrvEquiposClient : System.ServiceModel.ClientBase<Ventanas.SrvEquipos.ISrvEquipos>, Ventanas.SrvEquipos.ISrvEquipos {
        
        public SrvEquiposClient() {
        }
        
        public SrvEquiposClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SrvEquiposClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvEquiposClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvEquiposClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetAñoInicial() {
            return base.Channel.GetAñoInicial();
        }
        
        public System.Threading.Tasks.Task<int> GetAñoInicialAsync() {
            return base.Channel.GetAñoInicialAsync();
        }
        
        public int GetAñoFinal() {
            return base.Channel.GetAñoFinal();
        }
        
        public System.Threading.Tasks.Task<int> GetAñoFinalAsync() {
            return base.Channel.GetAñoFinalAsync();
        }
    }
}
