//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventanas.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IServiceBaseball2")]
    public interface IServiceBaseball2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseball2/DoWork", ReplyAction="http://tempuri.org/IServiceBaseball2/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseball2/DoWork", ReplyAction="http://tempuri.org/IServiceBaseball2/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseball2/jugador", ReplyAction="http://tempuri.org/IServiceBaseball2/jugadorResponse")]
        Modelo.Jugador jugador(string IdJugador, int año, string Idequipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseball2/jugador", ReplyAction="http://tempuri.org/IServiceBaseball2/jugadorResponse")]
        System.Threading.Tasks.Task<Modelo.Jugador> jugadorAsync(string IdJugador, int año, string Idequipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseball2/RellenarJugador", ReplyAction="http://tempuri.org/IServiceBaseball2/RellenarJugadorResponse")]
        void RellenarJugador(Modelo.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseball2/RellenarJugador", ReplyAction="http://tempuri.org/IServiceBaseball2/RellenarJugadorResponse")]
        System.Threading.Tasks.Task RellenarJugadorAsync(Modelo.Jugador jugador);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBaseball2Channel : Ventanas.ServiceReference2.IServiceBaseball2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBaseball2Client : System.ServiceModel.ClientBase<Ventanas.ServiceReference2.IServiceBaseball2>, Ventanas.ServiceReference2.IServiceBaseball2 {
        
        public ServiceBaseball2Client() {
        }
        
        public ServiceBaseball2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBaseball2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBaseball2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBaseball2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public Modelo.Jugador jugador(string IdJugador, int año, string Idequipo) {
            return base.Channel.jugador(IdJugador, año, Idequipo);
        }
        
        public System.Threading.Tasks.Task<Modelo.Jugador> jugadorAsync(string IdJugador, int año, string Idequipo) {
            return base.Channel.jugadorAsync(IdJugador, año, Idequipo);
        }
        
        public void RellenarJugador(Modelo.Jugador jugador) {
            base.Channel.RellenarJugador(jugador);
        }
        
        public System.Threading.Tasks.Task RellenarJugadorAsync(Modelo.Jugador jugador) {
            return base.Channel.RellenarJugadorAsync(jugador);
        }
    }
}
