//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventanas.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceBaseball")]
    public interface IServiceBaseball {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseball/DoWork", ReplyAction="http://tempuri.org/IServiceBaseball/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseball/DoWork", ReplyAction="http://tempuri.org/IServiceBaseball/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseball/GetAñoInicio", ReplyAction="http://tempuri.org/IServiceBaseball/GetAñoInicioResponse")]
        int GetAñoInicio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseball/GetAñoInicio", ReplyAction="http://tempuri.org/IServiceBaseball/GetAñoInicioResponse")]
        System.Threading.Tasks.Task<int> GetAñoInicioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseball/GetAñoFin", ReplyAction="http://tempuri.org/IServiceBaseball/GetAñoFinResponse")]
        int GetAñoFin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseball/GetAñoFin", ReplyAction="http://tempuri.org/IServiceBaseball/GetAñoFinResponse")]
        System.Threading.Tasks.Task<int> GetAñoFinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseball/GetEquiposAño", ReplyAction="http://tempuri.org/IServiceBaseball/GetEquiposAñoResponse")]
        Modelo.Equipo[] GetEquiposAño(int año);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseball/GetEquiposAño", ReplyAction="http://tempuri.org/IServiceBaseball/GetEquiposAñoResponse")]
        System.Threading.Tasks.Task<Modelo.Equipo[]> GetEquiposAñoAsync(int año);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseball/GetJugadoresEquipo", ReplyAction="http://tempuri.org/IServiceBaseball/GetJugadoresEquipoResponse")]
        Modelo.Jugador[] GetJugadoresEquipo(string equipo, int año);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseball/GetJugadoresEquipo", ReplyAction="http://tempuri.org/IServiceBaseball/GetJugadoresEquipoResponse")]
        System.Threading.Tasks.Task<Modelo.Jugador[]> GetJugadoresEquipoAsync(string equipo, int año);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBaseballChannel : Ventanas.ServiceReference1.IServiceBaseball, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBaseballClient : System.ServiceModel.ClientBase<Ventanas.ServiceReference1.IServiceBaseball>, Ventanas.ServiceReference1.IServiceBaseball {
        
        public ServiceBaseballClient() {
        }
        
        public ServiceBaseballClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBaseballClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBaseballClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBaseballClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public int GetAñoInicio() {
            return base.Channel.GetAñoInicio();
        }
        
        public System.Threading.Tasks.Task<int> GetAñoInicioAsync() {
            return base.Channel.GetAñoInicioAsync();
        }
        
        public int GetAñoFin() {
            return base.Channel.GetAñoFin();
        }
        
        public System.Threading.Tasks.Task<int> GetAñoFinAsync() {
            return base.Channel.GetAñoFinAsync();
        }
        
        public Modelo.Equipo[] GetEquiposAño(int año) {
            return base.Channel.GetEquiposAño(año);
        }
        
        public System.Threading.Tasks.Task<Modelo.Equipo[]> GetEquiposAñoAsync(int año) {
            return base.Channel.GetEquiposAñoAsync(año);
        }
        
        public Modelo.Jugador[] GetJugadoresEquipo(string equipo, int año) {
            return base.Channel.GetJugadoresEquipo(equipo, año);
        }
        
        public System.Threading.Tasks.Task<Modelo.Jugador[]> GetJugadoresEquipoAsync(string equipo, int año) {
            return base.Channel.GetJugadoresEquipoAsync(equipo, año);
        }
    }
}
